name: release
on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Verify commit exists in origin/main
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/main
    - name: Set VERSION variable from tag
      run: echo "VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION}
    - name: Test
      run: dotnet test --configuration Release /p:Version=${VERSION} --no-build
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .
    - name: Push
      run: dotnet nuget push CommandLine.${VERSION}.nupkg --source https://www.nuget.org --api-key oy2hdrfxjpirzhytnbwarmdiiclwqseubjqatrqaehvcfa
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
